### ISSUE TITLE
What tool will *apply* these changes?

### ISSUE THREAD

**Issue by howardjones** [Shoobx/xmldiff#10]
This is a neat tool, but whats the equivalent of patch(1) for this xmldiff?

I was hoping to use this patch type output to update XML configs during an ansible playbook...

**Comment by regebro** [comment]
I think this definitely is a feature we want, but I don't have the time to implement.

It would be fairly easy, the fact is that the XMLFormatter in 2.x does most of this already, but it would need to be extracted into a separate patch.py module, and a command line interface would need to be built.

**Comment by strichter** [comment]
@howardjones As @regebro pointed out, it should be easy to do. We are welcoming patches for those sort of improvements.

**Comment by howardjones** [comment]
I've moved on to my next challenges. Unfortunately my employer makes it complicated for me to contribute to open source. I was mainly asking because it *looks* like the output is intended to be machine readable or follows some existing spec.

**Comment by regebro** [comment]
It should be fairly easy to parse, yes, so we'll keep this issue open, because there definitely should be a patch command as well.

**Comment by regebro** [comment]
I've added a simple xmlpatch command, which will be included in the next release. Feedback is welcome.

**Comment by regebro** [comment]
Released 2.3.
