### ISSUE TITLE
Too many changes when deleting

### ISSUE THREAD

**Issue by Kyllian176** [Shoobx/xmldiff#106]
Hello, I tried to delete a "subelement" in a xml file : 

File1.xml :
`<alldatas>
  <text>random</text>
  <issue>
    <first>false</first>
    <second>false</second>
  </issue>
  <cancelData>false</cancelData>
  <client/>
  <time>0</time>
</alldatas>`

File2.xml : 
`<alldatas>
  <text>random</text>
  <issue>
    <first>false</first>
  </issue>
  <cancelData>false</cancelData>
  <client/>
  <time>0</time>
</alldatas>`

I tried : xmldiff file1.xml file2.xml

I expected the following result : 
`[delete, /alldatas/issue/second[1]]` (something like that)
But I got : 
`[move, /alldatas/issue/second[1], /alldatas[1], 2]
[rename, /alldatas/second[1], cancelData]
[delete, /alldatas/cancelData[2]]`

Is there any way to deal with "subelements" ? It works fine if I delete <cancelData> for example.

Thanks in advance.

**Comment by regebro** [comment]
With simple XML data with no attributes the content of the data is important, and the two nodes here have the same content, and then these things happens. In this case using `--fast-match` and making a simpler comparison actually gets better results, but in real world examples that's less common.
