### ISSUE TITLE
How can you ignore a particular field?

### ISSUE THREAD

**Issue by juneng603** [Shoobx/xmldiff#11]
I want to ignore some fields that are meaningless when comparing files. 
Is it available for current?

**Comment by regebro** [comment]
No, it is not, but it should be fairly easy to filter that out before comparing, with XSLT.

**Comment by juneng603** [comment]
@regebro Unfortunately, I can't modify the original data. If it doesn't work at xmldiff, I'll think about it at the top layer. Thank you for your answer.

**Comment by regebro** [comment]
Filtering it or stripping it out with XSLT is definitively an option in that case.
