### ISSUE TITLE
Official/recommended support channel?

### ISSUE THREAD

**Issue by velle** [Shoobx/xmldiff#130]
Is there any official or recommended place for getting support / asking questions? A mailinglist? Stackoverflow with some specific tag? If not, I can recomend using Github Discussions, which works very much like Github Issues, except its allowed to post things that are not strictly issues. You have chosen to list the email addresses of several of your contributors, which is appreciated, but my question is not urgent / essential enough that I will write people individually. Have a nice weekend :)

**Comment by regebro** [comment]
You can ask it here, I don't think there is enough traffic for a mailing list.
