### ISSUE TITLE
Support narrow python builds

### ISSUE THREAD

**Issue by bmurr** [Shoobx/xmldiff#17]
https://github.com/Shoobx/xmldiff/blob/39db5facd317e754afc78c9bda38b3756544c0d1/xmldiff/formatting.py#L90

I wanted to use this library in a scenario where the python runtime is provided for me.
Unfortunately this runtime is a narrow build and does not support unicode characters above 0x10000 and so fails near this line with the message:

`unichr() arg not in range(0x10000) `

I can simply patch the library to use the lower private use plane, 0xF8FF, but it would be nice if the library handled this for me or gave me a way to configure it.

By the way, thanks for this library, it's great!

**Comment by regebro** [comment]
That certainly sounds doable.

**Comment by regebro** [comment]
I think the 6400 character private use block at E000-F8FF should be sufficient for most use, so I just switched to using that. It also simplifies testing.

Once we no longer support Python version that have narrow/wide builds we can simply change it back. I did make it a module variable so people can override it if they like.

**Comment by regebro** [comment]
2.1 released.
