### ISSUE TITLE
How do I start? 

### ISSUE THREAD

**Issue by nradonic** [Shoobx/xmldiff#18]
Sorry, but I'm just picking up Python. Are there installation instructions? Make doesn't do anything. running setup.py doesn't do anything. Not sure about the process. There doesn't seem to be an installation file.

**Comment by regebro** [comment]
You typically install it with `pip`, for example `pip install xmldiff==2.0b7`. 

See also https://xmldiff.readthedocs.io/en/latest/installation.html

**Comment by nradonic** [comment]
Thanks. 

Sent from my iPhone
Nick
