### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by wisotzky** [Shoobx/xmldiff#2]
Features requested:
* Provide a Python API to simplify usage of xmldiff within your own python projects
* The API should support various inputs: XML trees, XML strings or XML files
* The output should be a Python list of dicts, containing the changes - to add your own post-processing

**Comment by regebro** [comment]
I've just released a beta version of xmldiff 2.0: https://pypi.org/project/xmldiff/2.0b1/
It does this, although the output is not a list of dicts, but a list of actions objects.
