### ISSUE TITLE
unexpected argument: diff_options in main.diff_files

### ISSUE THREAD

**Issue by YestinYang** [Shoobx/xmldiff#25]
Hi, by using current release version, xmldiff 2.0 on Sep 25, 2018, there is no `diff_options ` argument in diff_files / diff_texts (python API).

Seems it was added in GitHub after 2.0 released. May I know when will new version with `diff_options` argument be released? Thank you.

**Comment by strichter** [comment]
We are currently working on a set of optimizations that will be configurable through `diff_options`. Once those optimizations are complete, a new release will be created.

**Comment by regebro** [comment]
It should only be a few days, max.

**Comment by YestinYang** [comment]
Thanks all!
