### ISSUE TITLE
Empty diffs removal option?

### ISSUE THREAD

**Issue by TuulaP** [Shoobx/xmldiff#28]
Thanks for having this module available. I've two MARC XML files, where I've fixed the namespaces, so the xml files should be similar in that sense. I'm using the python API, by just giving it two xml trees:

```
diff = main.diff_trees(con1, con2,  formatter=formatting.XMLFormatter())
```

Otherwise things work as should, but I get lots of errors from the whitespace or line feeds between the elements. Is there option to hide these from difference results? 
```
    <diff:insert>
   </diff:insert>
```

I'll see if I can somehow fix these in either one of the originals, but if there some tricks in xmldiff, it would be great to know.

+Edit, attached an example, interestingly the command line xmldiff does ignore whitespace. 

xmldiff marctest1.xml marctest2.xml
[update-text, /mets:mets/marc21:record/marc21:leader[1], "01173cam a2200337 i 4500"]

Attached my test files. 
[marctest1.txt](https://github.com/Shoobx/xmldiff/files/2690088/marctest1.txt)
[marctest2.txt](https://github.com/Shoobx/xmldiff/files/2690089/marctest2.txt)

via python api I get for those files (first line is as expected, the rest not):
```
 python xmldifftest.py
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:marc21="http://www.loc.gov/MARC21/slim" xmlns:diff="http://namespaces.shoobx.com/diff">
  <marc21:record>
   <diff:insert> </diff:insert><marc21:leader>01<diff:delete>173</diff:delete><diff:insert>075</diff:insert>cam a22003<diff:delete>37</diff:delete><diff:insert>01</diff:insert> i 4500</marc21:leader>
   <diff:insert> </diff:insert><marc21:controlfield tag="001">425343</marc21:controlfield>
```

**Comment by regebro** [comment]
The formatters have flags for normalizing: WS_NONE, for no normalizing, WS_TAGS, for removing non-printable whitespace between tags, WS_TEXT to normalize inside text tags, and WS_BOTH to do both. The WS_TEXT makes no sense for the DiffFormatter (the default in the command line) but is only useful for the XMLFormatter()

The default for the XMLFormatter is to not normalize anything, but if you pass in XMLFormatter(normalizing=formatting.WS_BOTH) it should normalize as much as it can, and this should fix it.

**Comment by regebro** [comment]
I've updated the documentation on this:
https://xmldiff.readthedocs.io/en/latest/api.html#using-formatters
