### ISSUE TITLE
htmlformatter.xslt missing

### ISSUE THREAD

**Issue by dgilge** [Shoobx/xmldiff#29]
Just found this repo and it looks good!

Looks like the file `htmlformatter.xslt` is missing though.

https://github.com/Shoobx/xmldiff/blame/16df07461bb068fd080a97ce81be13fec1c124d5/docs/source/advanced.rst#L113

https://github.com/Shoobx/xmldiff/blob/e416303981f3424b0a2383d3edb25c405cac9dea/xmldiff/formatting.py#L15

**Comment by regebro** [comment]
Indeed, yes, I moved it to the documentation, as it's not a complete HTML differ by any means. 
https://github.com/Shoobx/xmldiff/blob/master/docs/source/static/htmlformatter.xslt

Apparently I missed removing that reference, I've fixed that. Thanks!
