### ISSUE TITLE
differ = diff.Differ() -- Where is this Differ() function/method available?

### ISSUE THREAD

**Issue by rkbala** [Shoobx/xmldiff#30]

**Comment by regebro** [comment]
Oups, sorry, that lime should have been deleted, it's not necessary after I implemented the diff_files(), diff_text() and diff_trees() functions in main. I fixed the Readme.

**Comment by rkbala** [comment]
Also you should remove it in the Project Description ("as a library" section) available in the link: https://pypi.org/project/xmldiff/
