### ISSUE TITLE
Enhancing namedtuples from DiffFormatter to also output left values and right xpath

### ISSUE THREAD

**Issue by rickykim93** [Shoobx/xmldiff#42]
Hi, I'm currently using xmldiff to diff two files and output nicely comparing left and right values. I really like the namedtuples, but seems to only output `left_xpath` (`node`) and right values (`value`,`text`,`position`,etc). I currently have a workaround searching left xpath in the original file to get the values, but I think others will find this helpful also if it's provided on the namedtuples itself.

I'm specifically talking about adding (`right_xpath` optional): 
`DeleteNode`:`lnode.tag`
`DeleteAttrib`:`left.attrib[key]`
`RenameNode`: `right_xpath`, `left.tag`
`UpdateTextIn`: `right_xpath`, `left.text`
`UpdateTextAfter`: `right_xpath`, `left.text`
`UpdateAttrib`: `right_xpath`, `left.attrib[key]`
`RenameAttrib`: `right_xpath`

I'm thinking about naming them `node_right` and `text_left` etc and leave the existing naming the same.

I will make a PR soon.

**Comment by regebro** [comment]
Closed after discussion on Pull Request. Also see https://github.com/Shoobx/xmldiff/issues/53
