### ISSUE TITLE
support of xml namespaces

### ISSUE THREAD

**Issue by happlek** [Shoobx/xmldiff#45]
i use xmldiff also for XML schema and missing the support of namespaces which i must patch via:

    class XsdDiffFormatter(formatting.XmlDiffFormatter):
        def __init__(self, normalize=formatting.WS_TAGS, pretty_print=False, base='', namespaces=None):
            formatting.XmlDiffFormatter.__init__(self, normalize=normalize, pretty_print=pretty_print)
            self.namespaces = namespaces
            self.base = base

        def _handle_InsertAttrib(self, action, orig_tree):
            value_text = "<@{0}>\n{1}\n</@{0}>".format(action.name, action.value)
            yield u"insert", action.node, value_text

            
        def _handle_InsertNode(self, action, orig_tree):
            if action.position == 0:
                yield u"insert-first", action.target, '<%s/>' % action.tag
                return
            sibling = orig_tree.xpath(self.base + action.target, namespaces=self.namespaces)[0][action.position - 1]
            yield u"insert-after", xmldiff_utils.getpath(sibling), '\n<%s/>' % action.tag

        def _handle_RenameAttrib(self, action, orig_tree):
            node = orig_tree.xpath(self.base + action.node, namespaces=self.namespaces)[0]
            value = node.attrib[action.oldname]
            value_text = "<@{0}>\n{1}\n</@{0}>".format(action.newname, value)
            yield u"remove", '%s/@%s' % (action.node, action.oldname)
            yield u"insert", action.node, value_text
    
        def _handle_MoveNode(self, action, orig_tree):
            if action.position == 0:
                yield u"move-first", action.node, action.target
                return
            node = orig_tree.xpath(self.base + action.node, namespaces=self.namespaces)[0]
            target = orig_tree.xpath(self.base + action.target, namespaces=self.namespaces)[0]
            # Get the position of the previous sibling
            position = action.position - 1
            if node.getparent() is target:
                # Moving to a new lower position in the same target,
                # adjust previous sibling position:
                if target.index(node) <= position:
                    position += 1
    
            sibling = target[position]
            yield u"move-after", action.node, xmldiff_utils.getpath(sibling)

and overwrite the xpath expressions which must be use the namespaces

**Comment by regebro** [comment]
We also use it with namespaces and have fairly good testing for that, even, so I don't know what it is you are trying to fix.

**Comment by regebro** [comment]
Also here a replicable example of the problem would be helpful.

**Comment by regebro** [comment]
Closing with lack of feedback.
