### ISSUE TITLE
bug in formatter

### ISSUE THREAD

**Issue by happlek** [Shoobx/xmldiff#46]
the formatter can have a problem if the patch doesn't apply parallel in every step, so it is possible, that the access in the formatter via xpath of the action.node or action.target can be failed:

sibling = orig_tree.xpath(action.target)[0][action.position - 1]
node = orig_tree.xpath(action.node)[0]
target = orig_tree.xpath(action.target)[0]

because the patch are not applied to the orig_tree

**Comment by regebro** [comment]
I would need a replicable example.

**Comment by regebro** [comment]
Closing for lack of feedback.
