### ISSUE TITLE
Broken link on documentation page

### ISSUE THREAD

**Issue by RMPR** [Shoobx/xmldiff#47]
Extracted from [this page](https://xmldiff.readthedocs.io/en/stable/advanced.html) : https://xmldiff.readthedocs.io/en/stable/advanced.html
"The XSLT template above of course only handles a few cases, like inserted formatting and insert and delete tags (used below). A more complete XSLT file is included [here]((file:///_static/htmlformatter.xslt))."
[broken link](file:///_static/htmlformatter.xslt) : file:///_static/htmlformatter.xslt

**Comment by regebro** [comment]
Yeah, all attempts of making this work with relative links (which would be the nicest) have failed. I've changed this to a direct link to github instead. That has the risk of the link failing in the future, but it's the best I can do.
