### ISSUE TITLE
Can we compare two XML file with same name sitting under two different folder? 

### ISSUE THREAD

**Issue by jbhatt091** [Shoobx/xmldiff#48]
I want to use XML Diff to compare list of XML files present under two separate folders. I am iterating through list of files present in two folders and passing each of them one by one in the compare function where I am using "diff_files" to identify difference in the file. When I have two different file names, it gives me the difference something like below:

 <title diff:insert="">ABCCCC</title><diff:insert>
 </diff:insert><title diff:delete="">XYZZZ</title>

But my necessity is to compare two files with same name. Is it possible do it with xml diff? Below is the sample code that I tried:

def FileCompare (golden_path,golden_File,Output_path,Output_File):
	
	try:
		gold_file=golden_File
		Out_file = Output_File
		gold_path=golden_path +"\\"+golden_File 
		Out_path =Output_path +"\\"+Output_File

		print('Files being compared',gold_path, gold_file, Out_path, Out_file)
		result = main.diff_files(gold_file, Out_file, formatter=formatting.XMLFormatter())
		print (result)

	except:
		print(traceback.format_exc())
		pass

for x in range(0,len(Comm_Files)):
	FileCompare(Source_Filenames[x][0],Comm_Files[x],Dest_Filenames[x][0],Comm_Files[x])

When I run above code, it doesnt show the difference instead, it simply prints parsed gold_file (File 1 from Folder 1) as below:

Initializing Dialogue...
Please select a directory.
Files being compared Folder2 Path File1.xml, Folder 2 Path File1.xml

<ClinicalDocument>
        <code code="55182-0" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Quality Measure Report"/>
        <title>XYZZZ</title>
        <effectiveTime value="20190717153758"/>
        <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
        <languageCode code="en"/>
        <recordTarget>
                <patientRole>
                        <addr use="HP">
                                <streetAddressLine>1</streetAddressLine>
                                <streetAddressLine>1</streetAddressLine>
                        </addr>
                        <telecom use="WP" value="tel:+1-123-456-7890"/>
                </patientRole>
        </recordTarget>
</ClinicalDocument>

**Comment by prashantmalviya99** [comment]
now i have to seen that compare two xml file but the problem having can we generate a new xml file from those xml file.

**Comment by regebro** [comment]
Yes, you can use the xml formatter, `xmldiff -f xml <file1> <file2>`, this will give you an XML output that has XML tags marking different items as deleted and inserted, etc.

**Comment by regebro** [comment]
Close as answered.
