### ISSUE TITLE
Return result in diff_command instead of printing

### ISSUE THREAD

**Issue by Utkarsh1308** [Shoobx/xmldiff#49]
Returning the result will make it easier to get the xml diff when the xmldiff library is imported in other projects,

**Comment by regebro** [comment]
The result is being returned, so I'm not sure what you are saying.

**Comment by Utkarsh1308** [comment]
I'm suggesting `return result` instead of printing the result on this [line](https://github.com/Shoobx/xmldiff/blob/master/xmldiff/main.py#L112)

**Comment by regebro** [comment]
No, that function is what is called when you run it as a command line command, it needs to print it. Use the documented API functions instead, they do what you want.
