### ISSUE TITLE
XMLDiff doesnt return the entire xml path in the difference result

### ISSUE THREAD

**Issue by jbhatt091** [Shoobx/xmldiff#52]
I am trying to list difference with edit script but it doesn't return the entire path in "node". I am getting below result:

UpdateAttrib(node='/*/*[7]', name='root', value='2.16.840.1.113883.4.391.109.1001.310651.18565.20190829143007')
RenameNode(node='/*/*[10]', tag='{urn:hl7-org:v3}effectiveTime')

Below is my code: 

from xmldiff import main
result = main.diff_files(File1, File2)

Instead, I am looking for result like below (full path):

UpdateAttrib(node='/ClinicalDocument/id[1]', name='root', value='2.16.840.1.113883.4.391.109.1001.310651.18565.20190829143007')

How do I achieve this?

**Comment by regebro** [comment]
Can you give me the example XML's? Ultimately it's the lxml library that tells us the xpath to an element, but it's usually not that bad...

**Comment by jbhatt091** [comment]
[Sample_File_with_Diff_result_CSV.zip](https://github.com/Shoobx/xmldiff/files/3613857/Sample_File_with_Diff_result_CSV.zip)

Please see attached sample XML file. Basically, I am using xml diff to compare two files and for each file CSV will be generated with the diff result. I have added sample result CSV as well in the same zip folder.

**Comment by regebro** [comment]
Aha, I see, it's the default namespace that messes it up. There might be workarounds for that, but there might also be a reason that `lxml` uses paths like `/*/*[2]` when you have a default namespace. That would need investigation.

**Comment by jbhatt091** [comment]
Got it; I added code to clean up namespace and it resolved the issue. Appreciate your help; Thank you so much.
