### ISSUE TITLE
Arrays are starting at 1 rather than 0

### ISSUE THREAD

**Issue by ItsCinnabar** [Shoobx/xmldiff#59]
This is probably intended, because to me it seems like a big thing you would run into immediately... 

If I run a compare on my two xmls files I get a lot of items, here is an example of one:

InsertAttrib(node='/gfx/group[14]', name='name', value='Group35')

This is the 14th total <group>, but its the 13th _index_ of groups under gfx. It currently displays it as an [index]. This matters because when I then try to use this changed data in lxml or another tree editor I'll be off by one if I do something like tree.findall('group')[14] to pull out the data from it. In actuality I need to manually lower the group number to [13] in order to get the correct data for this new node.

If this is the intended purpose, I think the way you display that should be changed. If you want to simply be the 14th spot rather than the 13th index then it should not appear as a python array with [ ]. This would probably break a lot of peoples code who already manually lower 1 from every 'index' xmldiff ships out, so I don't know, maybe it's too late to change it..? Either way, at least now its logged in and if someone spends a while trying to figure out why their pulled data does not match what is being flagged as edited they can maybe find this. I did check the issues and didn't notice anything.

**Comment by regebro** [comment]
It is zero-based and starts at zero, so there is some misunderstanding here.
