### ISSUE TITLE
Update-Attribute failure

### ISSUE THREAD

**Issue by ItsCinnabar** [Shoobx/xmldiff#62]
There seems to be an issue with the detection of attribute updates. For instance, lets take these two xmls

`<?xml version="1.0" encoding="UTF-8"?>
<xml>
    <element name="name1">
		<subelement attrib1="attrib"/>
    </element>
	<element name="name1">
		<subelement attrib1="attrib"/>
    </element>
</xml>`

`<?xml version="1.0" encoding="UTF-8"?>
<xml>
    <element name="name1">
		<subelement attrib1="wtf"/>
    </element>
	<element name="name1">
		<subelement attrib1="attrib"/>
    </element>
</xml>`

Try running a compare on these two... don't see the issue? Switch it, so instead of running "xmldiff 1.xml 2.xml" run "xmldiff 2.xml 1.xml"

One way you will get the expected output of
[update-attribute, /xml/element[1]/subelement[1], attrib1, "attrib"]

The other way you will get 
[move, /xml/element[1], /xml[1], 1]
[update-attribute, /xml/element[1]/subelement[1], attrib1, "wtf"]

move?? Nothing moved. A single attribute was updated.

This gets even worse if we change the xml up a bit...  Try this one.
`<?xml version="1.0" encoding="UTF-8"?>
<xml>
    <element name="name1">
		<subelement attrib1="attrib"/>
    </element>
	<element2 name="name2">
		<subelement2 attrib1="attrib"/>
    </element2>
</xml>`

`<?xml version="1.0" encoding="UTF-8"?>
<xml>
    <element name="name1">
		<subelement attrib1="wtf"/>
    </element>
	<element2 name="name2">
		<subelement2 attrib1="attrib"/>
    </element2>
</xml>`

Compare them one way and you get the expected single update-attribute
[update-attribute, /xml/element/subelement[1], attrib1, "attrib"]

But compare them the other way....
[move, /xml/element[1], /xml[1], 1]
[rename, /xml/element2[1], element]
[update-attribute, /xml/element[1], name, "name1"]
[rename, /xml/element[2], element2]
[update-attribute, /xml/element2[1], name, "name2"]
[rename, /xml/element/subelement2[1], subelement]
[update-attribute, /xml/element/subelement[1], attrib1, "wtf"]
[rename, /xml/element2/subelement[1], subelement2]

**Comment by regebro** [comment]
You have two elements that are exactly the same in one file. Then you modify the first one in the second file. 

That first element will then be a perfect match for the second element, and hence the diff will move it. Ironically, in this case, the --fast-match algorithm will therefore be the best one. But that's unusual in real world examples.
