### ISSUE TITLE
ValueError: Unknown diff format due to wrong encoding of diff

### ISSUE THREAD

**Issue by slamer59** [Shoobx/xmldiff#81]
On windows with Powershell, 
I took for the exemple [insert-node.left.xml](https://github.com/Shoobx/xmldiff/blob/master/tests/test_data/insert-node.left.html)

`xmldiff .\insert-node.left.xml .\insert-node.right.xml > insert-gen.diff`

This lead on my machine to UTF 16 with BOM which is not read by xmlpatch

` xmlpatch.exe .\insert-gen.diff .\insert-node.left.xml` 
gives : `ValueError: Unknown diff format`

This error is raised here:
https://github.com/Shoobx/xmldiff/blob/c6f2e885fc4b67b816d6c665fa06ad06ffdf5d66/xmldiff/main.py#L207

and can be fixed by https://github.com/Shoobx/xmldiff/issues/80

This might work too:
`print(result.encode('utf-8'))`

**Comment by regebro** [comment]
Aha, so your console is in UTF-16. I have added a `--diff-encoding` parameter to `xmldiff`, which will be included in v2.5.

**Comment by lechuhuuha** [comment]
root@DESKTOP-VM3852R:/home/xml-compare# xmldiff -v
xmldiff 2.7.0

root@DESKTOP-VM3852R:/home/xml-compare# xmldiff --diff-encoding=utf8 old_docx/word/document.xml new_docx/word/document.x
ml
usage: xmldiff [-h] [-v] [--check] [-f {diff,xml,old}] [-w] [-p] [-F F] [--unique-attributes [UNIQUE_ATTRIBUTES]]
               [--ratio-mode {accurate,fast,faster}] [--fast-match | --best-match]
               [--ignored-attributes [IGNORED_ATTRIBUTES]]
               file1 file2
xmldiff: error: unrecognized arguments: --diff-encoding=utf8

seem like its nots working @regebro
