### ISSUE TITLE
Tag same attributes / same nodes 

### ISSUE THREAD

**Issue by SENIAN** [Shoobx/xmldiff#84]
Hi ,

I would like to tag same attributes and same nodes.

I already implemented an own DiffFormatter for my specificity. But i want to extend it in such a way that same values left and right will get a tag 'same'. The specific formatter can then decide if we need to keep or remove certain values if they are the same on the right or left. so called custom made __handlers to make sure of that. 
I don't see alot from the documentation in-depth documentation about how it internally exactly works other than the research paper included. Not sure also which parts were implemented and which parts are not.

Were would / could i start to implement this. I see some generator code which im completely not familiar with.

That would be nice.

**Comment by regebro** [comment]
But everything that doesn't change is the same, and the things that are changed are tagged as such.
So you can see the differences, without tagging the things that are not different as "same".
