### ISSUE TITLE
Update-text before and after

### ISSUE THREAD

**Issue by matthewkiely0** [Shoobx/xmldiff#90]
Hi there,

I want to compare the differences between two xmls such that for a given node, I can present the original properties of the node (text, attribs etc.) and its new properties. For example, update-text returns the updated text of a node but not (as far as I am aware) the original text before the update, I would like to present both texts. Any advice? Thank you

**Comment by regebro** [comment]
You would need to create a formatter that does this for you. The XML formatted will do this, but the output isn't easy to read.
