### ISSUE TITLE
Process exit code

### ISSUE THREAD

**Issue by lynnux** [Shoobx/xmldiff#91]
Then gnu diff tool will return 1 if there has different, but xmldiff seems always return 0 except that encounter error like tag mismattch.

**Comment by regebro** [comment]
Hmm, I haven't thought about using it to test if there *is* a difference. Just to generate a diff. 

As a workaround you can just check if it outputs anything. Adding a --check parameter that behaves like you want makes sense.

**Comment by Glamhoth** [comment]
I added such a parameter in #98.

**Comment by regebro** [comment]
Thanks for all the help @Glamhoth !
