### ISSUE TITLE
Either way too slow or stucked into infinite loop

### ISSUE THREAD

**Issue by VianneyMI** [Shoobx/xmldiff#94]
I tried it on xml files that are thousands of lines and are similar to help me better focus on the discrepancies between the two.
But it does not work. 
After more than 10 minutes, still no results.
Also it would be nice to add on the docs, how the outputs are formatted. As of now, we don't know what to expect.

![image](https://user-images.githubusercontent.com/59029806/205968179-15e48a96-9fb4-47a7-89c4-a87a5a4be238.png)

**Comment by regebro** [comment]
Please upload example files, so I can look into it.
