### ISSUE TITLE
PyPi release (wheel broken for python3.11)?

### ISSUE THREAD

**Issue by FrancescElies** [Shoobx/xmldiff#95]
Would it be possible to upload newer wheels to [pypi](https://pypi.org/project/xmldiff/#files), the latest wheel on mypy does not support python 3.11 but master does

That wheel on pyi, has the following causing syntax error under python 3.11
![image](https://user-images.githubusercontent.com/6558089/210526110-55a019b8-5ebf-4ea7-a71b-4dab1ef84250.png)

But master seems to have [fixed that](https://github.com/Shoobx/xmldiff/blob/master/xmldiff/_diff_match_patch_py3.py#L1921) and tests run green under python3.11 
![image](https://user-images.githubusercontent.com/6558089/210526482-a67249e7-1b40-4f5e-a2a0-84d7047c5c30.png)

**Comment by regebro** [comment]
I'll hopefully make a release this week.

**Comment by regebro** [comment]
Released v2.5.
